### PR TITLE
Deploy pympv on Windows

### PR DESCRIPTION
**Pull request by Luni-4**
This PR allows to deploy `pympv` on Windows.

When a new `pympv` version is released, all `libmpv` binaries, in addition to the related `.whl`, are uploaded alongside with the release.

I hope this is appreciated! Thanks in advance for your review! :)

### CODE REVIEW

**Comment by Luni-4** [comment]
@marcan 

I've created a `.whl` package that will be automatically added to a release alongside with the `libmpv` binaries. I've personally tested it on `Windows`, feel free to add to `PyPI` if you want, thanks!

**Comment by marcan** [comment]
Hi, sorry for the late reply. Can you explain the setup.py changes a bit more? In particular, the USE_CYTHON bit was intended so that releases of this package may ship cythonized already, so users do not need cython to build them.

The Windows build workflow looks good, thanks!

**Comment by Luni-4** [comment]
> Hi, sorry for the late reply. Can you explain the setup.py changes a bit more? In particular, the USE_CYTHON bit was intended so that releases of this package may ship cythonized already, so users do not need cython to build them.

Hello @marcan, don't worry for the late reply! I re-added the `USE_CYTHON` parameter. At the same time, now you can automatically deploy both `Windows` and `Linux` versions on `PyPI`. 

To make this PR work, you need to create a new `GitHub` secret called `pypi_password` containing the password of your `pypi` account. To create a secret look [here](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

To run the action instead, tag a commit and push it.

I've also updated the `Windows` package to one of the last `mpv` versions

> The Windows build workflow looks good, thanks!

Yay! :)

**Comment by rr-** [comment]
Hey @marcan us maintainers of bubblesub have created a fork of pympv thinking it was a dead project. Once @Luni-4 lands Windows support here (and possibly set up GH action deployments like in our fork) I'm more than fine with taking our fork down in order to reduce the fragmentation on the market. I hope you understand. Thanks

(It still would be good to have someone as a backup maintainer in case you're busy with other stuff.)

**Comment by marcan** [comment]
I'm happy to have co-maintainers! I myself took over the project (and put it on PyPI) as a dependency for [BlitzLoop](https://github.com/marcan/blitzloop) and a couple other minor scripts I have, and have been mostly implementing features I need and fixing things when they break for me, but I tend to jump around projects a lot so I'm prone to not touching things for a year or more as long as they don't break.

If you're all much more active users of the project it might make sense to hand off main maintainership, or otherwise at least add you as collaborators here. I'm happy if the project is alive and doesn't break BlitzLoop too much. I'd certainly rather hand over the reins than have a renamed fork, I have no personal attachment to the project and if other people are more qualified than me to maintain it then so be it :)

Bubblesub sounds cool btw, I'll have to give it a shot next time I need to mess with ASS, which might be quite soon. I need to get some karaoke info BlitzLoop, exported out to ASS, possibly edited and then converted to YTT; last time I had Aegisub in the middle but building that has been annoying recently...

**Comment by rr-** [comment]
Thanks for the response. I heard about Blitzloop, it's a cool project :D 

To be honest I'd prefer to be added as collaborators here rather than getting a complete handover, so that we don't have the same sort of bottleneck, but in the opposite direction. @Luni-4 what do you think?

I don't think that we're all that more active, Luni is working mostly on Windows ports and maintenance stuff, then again there's not a lot of room to add new features for a proxy library like this. Personally I'm like you and care mostly about the compatibility with bubblesub on Linux. But I can address pull requests and the like if needed, at least give them code reviews. I can't guarantee I'll iterate on the pull requesters' work myself, or implement issues that get raised.

**Comment by Luni-4** [comment]
> Once @Luni-4 lands Windows support here (and possibly set up GH action deployments like in our fork) I'm more than fine with taking our fork down in order to reduce the fragmentation on the market. I hope you understand.

This PR has the same changes of the `bubblesub` fork, so it's ready. When a `Github` secret will be created, @marcan can bump to a new version anytime :)

Oh, and I agree with taking down our fork.

> To be honest I'd prefer to be added as collaborators here rather than getting a complete handover, so that we don't have the same sort of bottleneck, but in the opposite direction. @Luni-4 what do you think?

I perfectly agree, thanks a lot for the offer @marcan! :)

> But I can address pull requests and the like if needed, at least give them code reviews. I can't guarantee I'll iterate on the pull requesters' work myself, or implement issues that get raised.

Same.

**Comment by marcan** [comment]
Sounds like we should just co-maintain then, I'll try to set things up so our bus factor is >1.

I've got a few things on my plate this week, but I'll make some time to review this and make sure I understand the deployment workflow, then merge and set up the permissions. If you don't hear back from me in a week or so, feel free to ping :)

**Comment by Luni-4** [comment]
@marcan 

Pinging you as requested :)

**Comment by Luni-4** [comment]
@marcan 

What are we going to do with this PR?

**Comment by rr-** [comment]
@marcan seconding :–]

**Comment by marcan** [comment]
I'm alive! Just a combination of too many things going on in my life and my Windows laptop having a broken screen that I need to find time to swap out first. I'll try to find some time to get it taken care of today, or if not, Monday at the latest.

**Comment by marcan** [comment]
Made a minor change to make non-cython builds work again for source distributions (which would be pre-cythonized, so they should use the .c file if cython isn't available). I'll merge and then rebase the commits in for history cleanliness.

Other than that, looks good. Since GitHub actions works off of committed files, I want to poke around a bit to get used to it and maybe make some changes, so I'll merge this as-is for now and tweak things later :)

**Comment by marcan** [comment]
I added an alternate path to the action to deploy to TestPyPi and did a test deploy of 0.7.0. Can you check that it looks good for your use case? I'll deploy 0.7.0 to the real PyPi once I get the OK (unless you have other changes you'd like to get into that release).

**Comment by Luni-4** [comment]
> Made a minor change to make non-cython builds work again for source distributions (which would be pre-cythonized, so they should use the .c file if cython isn't available). I'll merge and then rebase the commits in for history cleanliness.
> 
> Other than that, looks good. Since GitHub actions works off of committed files, I want to poke around a bit to get used to it and maybe make some changes, so I'll merge this as-is for now and tweak things later :)

Good catch! Thanks a lot for fixing it! :smiley: 

> I added an alternate path to the action to deploy to TestPyPi and did a test deploy of 0.7.0. Can you check that it looks good for your use case? I'll deploy 0.7.0 to the real PyPi once I get the OK (unless you have other changes you'd like to get into that release).

Yep, feel free to deploy the package on `TestPyPi` and I will test it (please put the link here, so I can install it), thanks!

**Comment by marcan** [comment]
It's already deployed! https://test.pypi.org/manage/project/pympv/releases/

**Comment by Luni-4** [comment]
Oh no, I need to sign in in order to use it

**Comment by marcan** [comment]
sorry, https://test.pypi.org/project/pympv/#history

**Comment by Luni-4** [comment]
Thanks! I will test it as soon as possible on `Windows` :smile_cat: 

@rr-  
Can you test on your system too, please?

**Comment by Luni-4** [comment]
It's strange, it seems `Windows` can't find the module anymore...

**Comment by Luni-4** [comment]
Sorry, my bad, I was using the wrong `Python` version, it works perfectly on `Windows`!

**Comment by marcan** [comment]
Should I wait for @rr- or are we good?

**Comment by Luni-4** [comment]
Since he uses `pympv` too, I guess we should wait for @rr-  :smiley:

**Comment by rr-** [comment]
I'm OK if something breaks I'll raise ruckus

**Comment by marcan** [comment]
Released as 0.7.0 on pypi!

**Comment by Luni-4** [comment]
Yay!

**Pull request merged**
